In [4]:
import numpy as np

# Тема “Вычисления с помощью Numpy”

## 1

In [5]:
A = np.array([1, 2, 3, 3, 1])
B = np.array([6, 8, 11, 10, 7])

In [7]:
c = np.array([A, B])

In [10]:
mean_a = np.mean(c.transpose(), axis=0)

In [11]:
mean_a

array([2. , 8.4])

## 2

In [12]:
a_centered = c.transpose() -mean_a

In [13]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## 3

In [14]:
a_centered_sp = a_centered*a_centered

In [19]:
a_centered_sp/(a_centered_sp.shape[0]-1)

array([[0.25, 1.44],
       [0.  , 0.04],
       [0.25, 1.69],
       [0.25, 0.64],
       [0.25, 0.49]])

In [22]:
import pandas as pd

# Тема “Работа с данными в Pandas”

## 1

In [23]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Тургенев', 'Чехов', 'Островский']})

In [26]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]})

## 2

In [27]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')

## 3

In [32]:
top5 = authors_price.sort_values(by='price',ascending=False).head(5)

In [33]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## 4

In [40]:
authors_stat = authors_price.copy()

In [47]:
authors_stat['max'] = authors_stat['author_id'].map(authors_stat.groupby(['author_id'])['price'].max())

In [49]:
authors_stat['min'] = authors_stat['author_id'].map(authors_stat.groupby(['author_id'])['price'].min())

In [50]:
authors_stat['mean'] = authors_stat['author_id'].map(authors_stat.groupby(['author_id'])['price'].mean())

In [51]:
authors_stat

author_id author_name            book_title  price    max    min  \
0          1.0    Тургенев           Отцы и дети  450.0  450.0  300.0   
1          1.0    Тургенев                 Рудин  300.0  450.0  300.0   
2          1.0    Тургенев     Дворянское гнездо  350.0  450.0  300.0   
3          2.0       Чехов      Толстый и тонкий  500.0  500.0  450.0   
4          2.0       Чехов       Дама с собачкой  450.0  500.0  450.0   
5          3.0  Островский                 Гроза  370.0  370.0  290.0   
6          3.0  Островский  Таланты и поклонники  290.0  370.0  290.0   
max        NaN         NaN                   NaN    NaN    NaN    NaN   

           mean  
0    366.666667  
1    366.666667  
2    366.666667  
3    475.000000  
4    475.000000  
5    330.000000  
6    330.000000  
max         NaN